name: kuran_gunlugu
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Bizim eklediklerimiz:
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  intl: ^0.18.0
  audioplayers: ^6.5.1
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.1
  share_plus: ^9.0.0
  screenshot: ^3.0.0
  path_provider: ^2.1.1
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  auto_size_text: ^3.0.0
  permission_handler: ^12.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  # ðŸ‘‡ YENÄ° DOSYA ADINI BURAYA YAZ
  image_path: "assets/icon_splash.png" 
  
  adaptive_icon_background: "#0F172A"
  # ðŸ‘‡ YENÄ° DOSYA ADINI BURAYA DA YAZ
  adaptive_icon_foreground: "assets/icon_splash.png" 
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: "#0F172A"
  # ðŸ‘‡ EN ALTA YAPIÅžTIR
flutter_native_splash:
  # EkranÄ± boyayacak renk (Koyu Lacivert)
  color: "#0F172A"
  
  # Ortaya koyacaÄŸÄ± resim (KÄ±rpÄ±lmÄ±ÅŸ, ÅŸeffaf PNG)
  image: "assets/icon_splash.png"
  
  # Android 12+ iÃ§in de aynÄ±sÄ±
  android_12:
    color: "#0F172A"
    image: "assets/icon_splash.png"
    # Ä°konun arka planÄ±nÄ± da aynÄ± renge boya (Garanti olsun)
    icon_background_color: "#0F172A"