name: kuran_gunlugu
description: A new Flutter project.
publish_to: 'none'
version: 1.0.2+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Bizim eklediklerimiz:
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  intl: ^0.18.0
  audioplayers: ^6.5.1
  google_fonts: ^6.1.0
  shared_preferences: ^2.5.4
  share_plus: ^9.0.0
  screenshot: ^3.0.0
  path_provider: ^2.1.1
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  flutter_timezone: ^3.0.1
  auto_size_text: ^3.0.0
  permission_handler: ^12.0.1
  purchases_flutter: ^8.11.0
  purchases_ui_flutter: ^8.11.0
  # Prayer times packages:
  adhan: ^2.0.0
  geolocator: ^12.0.0
  timer_builder: ^2.0.0
  hijri: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  change_app_package_name: ^1.5.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/cami_motif_tr.png
flutter_launcher_icons:
  flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  
  # 1. GENEL AYAR (Android Bunu Kullanacak - Eski Ã‡alÄ±ÅŸan AyarÄ±n) ðŸ›¡ï¸
  image_path: "assets/icon_splash_kucuk.png"
  
  # 2. ANDROID ADAPTIVE AYARLARI ðŸ¤–
  adaptive_icon_background: "#0F172A"
  adaptive_icon_foreground: "assets/icon_splash_kucuk.png"
  min_sdk_android: 21

  # 3. iOS Ã–ZEL AYARI (Genel ayarÄ± ezer, bunu kullanÄ±r) ðŸŽ
  image_path_ios: "assets/icon_ios.png"
  remove_alpha_ios: true
  background_color_ios: "#0F172A"
flutter_native_splash:
  # EkranÄ± boyayacak renk (Koyu Lacivert)
  color: "#0F172A"
  
  # Ortaya koyacaÄŸÄ± resim (KÄ±rpÄ±lmÄ±ÅŸ, ÅŸeffaf PNG)
  image: "assets/icon_splash.png"
  
  # Android 12+ iÃ§in de aynÄ±sÄ±
  android_12:
    color: "#0F172A"
    image: "assets/icon_splash.png"
    # Ä°konun arka planÄ±nÄ± da aynÄ± renge boya (Garanti olsun)
    icon_background_color: "#0F172A"